In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.read_csv('C:\\Users\PRASHANT\\Desktop\\coding dec19\\weather-data-in-new-york-city-2016\\ex1data1.csv')
df2=pd.read_csv('C:\\Users\PRASHANT\\Desktop\\coding dec19\\weather-data-in-new-york-city-2016\\ex1data2.csv')

In [3]:
df1.head()

6.1101   17.592
0  5.5277   9.1302
1  8.5186  13.6620
2  7.0032  11.8540
3  5.8598   6.8233
4  8.3829  11.8860

In [4]:
df2.head()

2104  3  399900
0  1600  3  329900
1  2400  3  369000
2  1416  2  232000
3  3000  4  539900
4  1985  4  299900

In [5]:
#df1.iloc[0:2] select row 0 to 2
#iloc select data by row no
#loc select data by conditional statement

In [6]:
 # X=df1.iloc[[0,1],[0]] it select 0 and 1 row and 0th column
# X=df1.iloc[1:3,[1]]    it select row 1 to row 2 (exclude row3) and column 1 (index start with 0) 

In [7]:
 #it select all row and 0th column of data

    # variable=earlier_data_frame_name.iloc[row_to_select:column_to_select]


In [8]:
X=df1.iloc[:,[0]] #select  all row and 0 column no
X.shape

(96, 1)

In [52]:
X.mean()        #population

4.590575520833333

In [10]:
Y=df1.iloc[:,[1]] #profit

In [51]:
Y.mean()

17.592    5.716709
dtype: float64

In [12]:
m,n=X.shape

In [13]:
m  #m contain no of rows

96

In [14]:
#now adding a X0 as column of ones
X1=np.ones([96,1])
print(X1.shape,X.shape)

(96, 1) (96, 1)


In [15]:
X=np.hstack([X1,X])

In [16]:
X

array([[ 1.    ,  5.5277],
       [ 1.    ,  8.5186],
       [ 1.    ,  7.0032],
       [ 1.    ,  5.8598],
       [ 1.    ,  8.3829],
       [ 1.    ,  7.4764],
       [ 1.    ,  8.5781],
       [ 1.    ,  6.4862],
       [ 1.    ,  5.0546],
       [ 1.    ,  5.7107],
       [ 1.    , 14.164 ],
       [ 1.    ,  5.734 ],
       [ 1.    ,  8.4084],
       [ 1.    ,  5.6407],
       [ 1.    ,  5.3794],
       [ 1.    ,  6.3654],
       [ 1.    ,  5.1301],
       [ 1.    ,  6.4296],
       [ 1.    ,  7.0708],
       [ 1.    ,  6.1891],
       [ 1.    , 20.27  ],
       [ 1.    ,  5.4901],
       [ 1.    ,  6.3261],
       [ 1.    ,  5.5649],
       [ 1.    , 18.945 ],
       [ 1.    , 12.828 ],
       [ 1.    , 10.957 ],
       [ 1.    , 13.176 ],
       [ 1.    , 22.203 ],
       [ 1.    ,  5.2524],
       [ 1.    ,  6.5894],
       [ 1.    ,  9.2482],
       [ 1.    ,  5.8918],
       [ 1.    ,  8.2111],
       [ 1.    ,  7.9334],
       [ 1.    ,  8.0959],
       [ 1.    ,  5.6063],
 

In [17]:
theta=np.zeros([2,1])

In [18]:
theta

array([[0.],
       [0.]])

In [29]:
alpha=0.01
print(X.shape,type(X))

(96, 2) <class 'numpy.ndarray'>


In [30]:
X2=X.dot(theta)-Y
print(X2.shape,type(X2))
X3=X2**2 #perform element wise square
cost=(1/(2*m))*np.sum(X3)



(96, 1) <class 'pandas.core.frame.DataFrame'>


In [31]:
cost=float(cost)


In [32]:
print(cost)

30.79495785534583


In [43]:
X7=np.array([X[:,1]]).T
print(X7.shape)
print(type(X7))

(96, 1)
<class 'numpy.ndarray'>


In [45]:
#X7.shape
#X7=pd.DataFrame(X7)
#print(X7)
print(X2.shape,X7.shape,type(X2),type(X7))
X2=np.array(X2)
X7=np.array(X7)
X = np.array(X)
#print(X2)
print(X2.shape,X7.shape,type(X2),type(X7))

(96, 1) (96, 1) <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(96, 1) (96, 1) <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [47]:

X2=np.array(X.dot(theta)-Y)
X4=(1/m)*np.sum(X2)*alpha
print(X2.shape,X7.shape,type(X2),type(X7))
X5=X2*X7
#X7=np.zeroes()
#print("x2 x7 product is ",X2*X7)

#for i1 in range(m):
    
print(X5.shape)
#print(X2)
#print(X7)
print(X5)

(96, 1) (96, 1) <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(96, 1)
[[ -50.46900654]
 [-116.3811132 ]
 [ -83.0159328 ]
 [ -39.98317334]
 [ -99.6391494 ]
 [ -32.50963012]
 [-102.9372    ]
 [ -42.80048794]
 [ -19.29138636]
 [ -18.57233854]
 [-219.61282   ]
 [ -18.0913434 ]
 [ -60.75741672]
 [  -4.03975653]
 [ -18.89729426]
 [ -33.76717392]
 [  -2.87680618]
 [ -23.47961328]
 [ -38.10666244]
 [ -19.42510926]
 [-441.21709   ]
 [ -23.4042963 ]
 [ -32.81664375]
 [ -17.15380425]
 [-428.87691   ]
 [-173.190828  ]
 [ -77.2106919 ]
 [-193.581792  ]
 [-536.135841  ]
 [   6.407928  ]
 [ -39.51399604]
 [-112.2176588 ]
 [ -10.8968841 ]
 [ -53.72194286]
 [ -36.19455082]
 [ -33.32596276]
 [ -19.02105464]
 [-129.861812  ]
 [ -34.92718116]
 [  -3.00931833]
 [ -26.92089875]
 [ -63.0522632 ]
 [ -14.09129222]
 [ -52.67431546]
 [  -7.42151053]
 [ -26.02888574]
 [ -10.6977816 ]
 [ -93.65031   ]
 [  -5.64079464]
 [ -50.89936608]
 [  -9.76404492]
 [ -31.83739515]
 [ -38.00105411]
 [  -9.01347424]
 [   9.036

In [48]:
X6=(1/m)*np.sum(X5)*alpha
print(theta[1].shape)
X6.shape

(1,)


()

In [49]:
X2=X.dot(theta)-Y
X3=X2**2 #perform element wise square
cost=(1/(2*m))*np.sum(X3)
cost=float(cost)
print(cost)

30.79495785534583


In [50]:


for i1 in range(1500):
    X2=X.dot(theta)-Y
    X4=(1/m)*np.sum(X2)*alpha
    X5=X2*X7
    X6=(1/m)*np.sum(X5)*alpha
    
    theta[0]=theta[0]-X4
    theta[1]=theta[1]-X6
    #calculating cost after each iteration
    X2=X.dot(theta)-Y
    X3=X2**2 #perform element wise square
    cost=(1/(2*m))*np.sum(X3)
    cost=float(cost)
    if i1%100==0:
        print("i1 = {}, cost = {} ".format(i1,cost))
    

i1 = 0, cost = 5.901469393444239 
i1 = 100, cost = 4.6246435813266675 
i1 = 200, cost = 4.2711910513608515 
i1 = 300, cost = 4.024967772240886 
i1 = 400, cost = 3.8534428911303977 
i1 = 500, cost = 3.7339546569345026 
i1 = 600, cost = 3.650716365097088 
i1 = 700, cost = 3.592730628889357 
i1 = 800, cost = 3.5523364121252734 
i1 = 900, cost = 3.5241968582505376 
i1 = 1000, cost = 3.504594188470013 
i1 = 1100, cost = 3.490938511331888 
i1 = 1200, cost = 3.4814256480235457 
i1 = 1300, cost = 3.474798765489061 
i1 = 1400, cost = 3.4701823244972783 


In [ ]:
print(theta)