In [172]:
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  #importing libraray
import math
import scipy.optimize as opt

In [173]:


def sigmoid(x):
    return 1 / (1 + np.exp(-x))  #sigmoid fn


In [174]:
data = loadmat('C:\\Users\\PRASHANT\\Desktop\\coding dec19\\file_neural\\ex3data1.mat')

In [175]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [176]:
type(data)

dict

In [177]:
theta_all = loadmat('C:\\Users\\PRASHANT\\Desktop\\coding dec19\\file_neural\\ex3weights.mat')

In [178]:
theta_all

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Tue Oct 18 14:57:02 2011',
 '__version__': '1.0',
 '__globals__': [],
 'Theta1': array([[-2.25623899e-02, -1.05624163e-08,  2.19414684e-09, ...,
         -1.30529929e-05, -5.04175101e-06,  2.80464449e-09],
        [-9.83811294e-02,  7.66168682e-09, -9.75873689e-09, ...,
         -5.60134007e-05,  2.00940969e-07,  3.54422854e-09],
        [ 1.16156052e-01, -8.77654466e-09,  8.16037764e-09, ...,
         -1.20951657e-04, -2.33669661e-06, -7.50668099e-09],
        ...,
        [-1.83220638e-01, -8.89272060e-09, -9.81968100e-09, ...,
          2.35311186e-05, -3.25484493e-06,  9.02499060e-09],
        [-7.02096331e-01,  3.05178374e-10,  2.56061008e-09, ...,
         -8.61759744e-04,  9.43449909e-05,  3.83761998e-09],
        [-3.50933229e-01,  8.85876862e-09, -6.57515140e-10, ...,
         -1.80365926e-06, -8.14464807e-06,  8.79454531e-09]]),
 'Theta2': array([[-0.76100352, -1.21244498, -0.10187131, -2.36850085, -1.057781

In [179]:
type(theta_all)

dict

In [180]:
theta1=theta_all['Theta1']
theta2=theta_all['Theta2']
# swap first and last columns of Theta2, due to legacy from MATLAB indexing, 
# since the weight file ex3weights.mat was saved based on MATLAB indexing
theta2 = np.roll(theta2, 1, axis=0)
print(theta1.shape)
print(theta2.shape)

(25, 401)
(10, 26)


In [181]:
XX=data['X']
print(XX.shape,type(XX))
#=annots['y']
Y = data['y']
print(Y)
print(Y.shape,type(Y))
np.place(Y, Y == 10, 0)
print(Y[4000:5000,:])

(5000, 400) <class 'numpy.ndarray'>
[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]
(5000, 1) <class 'numpy.ndarray'>
[[8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8

In [182]:
m,n=XX.shape
x0=np.ones([m,1])
X=x0
print(X.shape)

(5000, 1)


In [183]:
#here we take output all column one by one normalise it and then stack then together
# also we stack a column of one as first column
X=np.ones([m,1])  
div_normaliser=[]#we store factor by which divide each element of feature before passing to hypothesis
sub_normaliser=[] #we store factor by which substarct each element of feature before passing to hypothesis

#for normalisating each feature  we first substarct with mean then divide by standard deviation of each fature

for j in range(0,n):   # nth column will not be included there are n column in X 0 to n-1
    x1=XX[:,[j]]
    #print(x1)
    x1=np.array(x1)
    #print(x1)
    #sub_normaliser.append(x1.mean()) #soring for further
    #print("x1 mean is ",x1.mean())

   # x1=(x1-x1.mean())# substract each element with mean of that feature
    
    #div_normaliser.append(x1.std())#storing for further calculation
    #print("x1 standard deviation is ",x1.std())
    #x1=x1/x1.std()
     
    
    #print(x1.shape,type(x1))
    X=np.hstack([X,x1])   #one by one add all column

print(X.shape,type(X))

#we get n+1 column in input as column of ones is added


(5000, 401) <class 'numpy.ndarray'>


In [184]:


print(Y.shape,type(Y))
print(X.shape,type(X))
print(Y)

(5000, 1) <class 'numpy.ndarray'>
(5000, 401) <class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [185]:
n_label=10


print(theta1.shape)
print(theta2.shape)

print(X.shape)

print(type(X))

(25, 401)
(10, 26)
(5000, 401)
<class 'numpy.ndarray'>


In [186]:
A1=sigmoid(X.dot(theta1.T))
print(A1.shape)
a1=np.ones([A1.shape[0],1])
A1=np.hstack([a1,A1])

(5000, 25)


In [187]:


#print("A1 is ",A1)
print(A1.shape)
A2=sigmoid(A1.dot(theta2.T))
print(A2.shape)
output=np.argmax(A2, axis=1)
print(Y)
output=output.reshape((Y.shape))
print(output)




(5000, 26)
(5000, 10)
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [188]:
print("Training accuracy:", str(100 * np.mean(output == Y)) + "%")

Training accuracy: 97.52%


In [189]:
print(Y.shape)
print(output.shape)


(5000, 1)
(5000, 1)
